export const DISPLAY_ALERT = 'SHOW_ALERT'

export const CLEAR_ALERT = 'CLEAR_ALERT'
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = ' REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = ' REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = ' LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = ' LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_POST_BEGIN = 'CREATE_POST_BEGIN'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const GET_POST_BEGIN = 'GET_POST_BEGIN'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'

export const SET_EDIT_POST = 'SET_EDIT_POST'

export const DELETE_POST_BEGIN = 'DELETE_POST_BEGIN'

export const EDIT_POST_BEGIN = 'EDIT_POST_BEGIN'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const CREATE_HEALTH_POST_BEGIN = 'CREATE_HEALTH_POST_BEGIN'
export const CREATE_HEALTH_POST_SUCCESS = 'CREATE_HEALTH_POST_SUCCESS'
export const CREATE_HEALTH_POST_ERROR = 'CREATE_HEALTH_POST_ERROR'

export const GET_HEALTH_POST_BEGIN = 'GET_HEALTH_POST_BEGIN'
export const GET_HEALTH_POST_SUCCESS = 'GET_HEALTH_POST_SUCCESS'

export const SET_EDIT_HEALTH_POST = 'SET_EDIT_HEALTH_POST'

export const DELETE_HEALTH_POST_BEGIN = 'DELETE_HEALTH_POST_BEGIN'


export const EDIT_HEALTH_POST_BEGIN = 'EDIT_HEALTH_POST_BEGIN'
export const EDIT_HEALTH_POST_SUCCESS = 'EDIT_HEALTH_POST_SUCCESS'
export const EDIT_HEALTH_POST_ERROR = 'EDIT_HEALTH_POST_ERROR'

export const CREATE_EVENT_BEGIN = 'CREATE_EVENT_BEGIN'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR'


